#application: darringtonteals2
#version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /dist
  static_dir: dist

- url: /public/(.*)
  static_files: public/\1
  upload: public/(.*)
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /.*
  script: main.app

skip_files:
- ^(node_modules)
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$

libraries:
- name: ssl
  version: latest